Removal of RequiredWith as part of linux and windows virtual machine resources
As the `platform_fault_domain` has a default value, this causes the validation
to fire as follows:

```
    error: azure:compute/linuxVirtualMachine:LinuxVirtualMachine resource 'exampleLinuxVirtualMachine' has a problem: "platform_fault_domain": all of `platform_fault_domain,virtual_machine_scale_set_id` must be specified
```

We need to ensure that a default value doesn't fire this warning. We still have the
docs that suggest that the 2 values are required with each other